# /// script
# requires-python = ">=3.10"
# dependencies = ["panchi>=2.0.0", "python-pptx>=1.0", "pyyaml>=6.0", "pydantic>=2.0", "sympy>=1.12", "pillow>=10"]
# ///
"""Locate the next session and set up its folder.

Usage:
    new_session.py COURSE_DIR                    # the next session after today
    new_session.py COURSE_DIR --date 2026-09-24

Prints what the prep needs to know (week, sections, goals, session number, notes,
the latest confidence tallies) and creates sessions/<date>/ with:
    questions.yaml   empty list, to be drafted
    feedback.md      the three-pass template (Prep review filled during prep)
    build.sh         verify → deck.yaml → build → validate → render, with absolute paths

It never overwrites an existing file. It also seeds lessons.md's header from
course.yaml if it still says "MATH 0000".

The session number comes only from course.yaml (schedule[].sessions). It is never
inferred; if it is missing, or disagrees with the folders in sessions/, the
output says so and the skill asks the leader once.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from confidence import latest_confidence  # noqa: E402
from schemas import Course, SchemaError, load_course  # noqa: E402

SCRIPTS = Path(__file__).resolve().parent
DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

FEEDBACK = """# Feedback — {date}

## Prep review
<!-- session-prep: changes the leader asked for at the plan checkpoint and after seeing the deck; pushback and how it resolved -->
-

## Edits after generation
<!-- session-feedback: interpreted diff of deck.generated.pptx vs the presented deck -->
-

## Post-session
Attendance:
Timing vs plan:
What worked:
What fell flat / confused people:
Where students struggled:
For next time:

## Confidence
Topic asked:
Start: 1×_ 2×_ 3×_ 4×_ 5×_   (n = _)
End:   1×_ 2×_ 3×_ 4×_ 5×_   (n = _)

## Lessons extracted
<!-- session-feedback: what was added/changed in lessons.md because of this session -->
-
"""

BUILD = """#!/usr/bin/env bash
# Generated by new_session.py — rebuild the deck for {date}: bash "{session}/build.sh"
# verify → deck.yaml → build → validate → render. Stops at the first failure.
# Refuses to overwrite hand edits in deck.pptx; FORCE=1 overrides.
set -euo pipefail
S="{session}"
K="{scripts}"

uv run "$K/verify_runner.py" "$S"
uv run "$K/render_questions.py" "$S" --only deck
if [[ -f "$S/deck.pptx" && -f "$S/deck.generated.pptx" && "${{FORCE:-0}}" != 1 ]] && ! cmp -s "$S/deck.pptx" "$S/deck.generated.pptx"; then
  echo "deck.pptx has hand edits since the last build — FORCE=1 to overwrite, or build to another file." >&2
  exit 3
fi
uv run "$K/build_deck.py" "$S/deck.yaml"{template_args} -o "$S/deck.pptx"
cp "$S/deck.pptx" "$S/deck.generated.pptx"
uv run "$K/validate_deck.py" "$S/deck.pptx" --deck "$S/deck.yaml"{template_args}
uv run "$K/render.py" "$S/deck.pptx" --out "$S/render" || echo "render skipped (see doctor.py)" >&2
"""


def next_session_date(course: Course, today: dt.date) -> dt.date:
    explicit = sorted(s.date for w in course.schedule for s in w.sessions if s.date > today)
    if explicit:
        return explicit[0]
    days = {DAYS.index(d[:3].title()) for d in course.session.days}
    d = today + dt.timedelta(days=1)
    while d.weekday() not in days:
        d += dt.timedelta(days=1)
    return d


def seed_lessons(course_dir: Path, course: Course) -> bool:
    lessons = course_dir / "lessons.md"
    code = course.course.split("—")[0].split(" - ")[0].strip()
    header = f"# Lessons — {code}{', ' + course.term if course.term else ''}"
    if not lessons.exists():
        lessons.write_text(
            f"{header}\n\n<!-- Maintained by the session-feedback skill; read first by session-prep. Keep it short. -->\n\n"
            "## Preferences\n\n## Students\n\n## Timing\n\n## Revisit\n"
        )
        return True
    text = lessons.read_text()
    if text and "MATH 0000" in text.splitlines()[0]:
        lessons.write_text(re.sub(r"^# .*", header, text, count=1))
        return True
    return False


def setup(course_dir: Path, date: dt.date | None, today: dt.date | None = None) -> dict:
    course = load_course(course_dir / "course.yaml")
    today = today or dt.date.today()
    date = date or next_session_date(course, today)
    week = course.week_for(date)
    number = course.session_number(date)
    sessions = course_dir / "sessions"
    earlier = (
        sorted(p.name for p in sessions.glob("20*-*-*") if p.is_dir() and p.name < date.isoformat()) if sessions.exists() else []
    )

    info: dict = {"date": date.isoformat(), "session_number": number, "notes": []}
    if week:
        info |= {"week": week.week, "sections": week.sections, "goals": week.goals, "week_notes": week.notes}
    else:
        info["notes"].append(f"{date} is before the first week in course.yaml's schedule")
    if number is None:
        info["notes"].append(
            f"course.yaml has no session number for {date}; ask the leader and add it under that week's `sessions:`"
        )
    else:
        numbered = {s.date.isoformat(): s.number for w in course.schedule for s in w.sessions}
        prev = [numbered[e] for e in earlier if e in numbered]
        if prev and max(prev) >= number:
            info["notes"].append(
                f"session {number} is not after earlier sessions in sessions/ (up to {max(prev)}); ask the leader once"
            )
        elif len(earlier) + 1 != number and not prev:
            info["notes"].append(
                f"course.yaml says session {number}, but sessions/ has {len(earlier)} earlier folders; ask the leader once if unsure"
            )

    if seed_lessons(course_dir, course):
        info["notes"].append("seeded lessons.md header from course.yaml")

    folder = sessions / date.isoformat()
    folder.mkdir(parents=True, exist_ok=True)
    created = []
    template = course_dir / "template.pptx"
    template_args = ""
    if template.exists():
        template_args = f' --template "{template.resolve()}" --map "{(course_dir / "template-map.yaml").resolve()}"'
    files = {
        "questions.yaml": "[]\n",
        "feedback.md": FEEDBACK.format(date=date.isoformat()),
        "build.sh": BUILD.format(date=date.isoformat(), session=folder.resolve(), scripts=SCRIPTS, template_args=template_args),
    }
    for name, content in files.items():
        path = folder / name
        if not path.exists():
            path.write_text(content)
            created.append(name)
    (folder / "build.sh").chmod(0o755)
    info["folder"] = str(folder.resolve())
    info["created"] = created

    conf = latest_confidence(course_dir, before=date)
    if conf:
        info["latest_confidence"] = conf
    return info


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("course", type=Path)
    parser.add_argument("--date", type=dt.date.fromisoformat)
    args = parser.parse_args()
    try:
        info = setup(args.course.resolve(), args.date)
    except SchemaError as e:
        sys.exit(f"new_session: {e}")
    import yaml

    print(yaml.safe_dump(info, sort_keys=False, allow_unicode=True))


if __name__ == "__main__":
    main()
